CDP4WebServices.API/Cdp4Bootstrapper.cs
Add CORS headers in the `override RequestStartup` method of the bootstrapper. Verified with a test blazor app that CDP4ServicesDal-CE and WspDal can open a session and return the `SiteDirectory` POCO
=> [Add] CORS headers to support Blazor (and other framework) web-app development; fixes #60

CDP4WebServices.API.Tests/OperationProcessorTestFixture.cs, CDP4WebServices.API/Services/BusinessLogic/IOldParameterContextProvider.cs, CDP4WebServices.API/Services/BusinessLogic/Implementation/OldParameterContextProvider.cs, CDP4WebServices.API/Services/Operations/OperationProcessor.cs, CDP4WebServices.API/Services/Supplemental/ParameterService.cs
a fix for https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/62. Too many objects are stil being returned though for which a new issue should be created. Since in the database a reorder is an update on the items of the list, not the container of the list... This is caused by the trigger that updates the revision of Things that are added, updated or deleted. This trigger is "too trigger happy".
=> Update OperationProcessor to take reordering into account for updating the container as well

CDP4Orm.Tests/CDP4Orm.Tests.csproj, CDP4Orm/CDP4Orm.csproj, CDP4WebServices.API.Tests/CDP4WebServices.API.Tests.csproj, CDP4WebServices.API/CDP4WebServices.API.csproj, CDP4WebServices.API/Modules/10-25/ApiBase.cs, CDP4WebServices.API/Services/BusinessLogic/Implementation/EngineeringModelZipExportService.cs, Nuget.Config
[Fix] an issue for a SiteReferenceDataLibrary HashSet
[Add] a little bit more comprehensible error messages from the server and some necessary checks
The issue was that SiteReferenceDataLibrary HashSet relied on default equality implementation which is link comparison, but the code produces SRDLs dtos that are equal, but because they have different links they were added and zip failed for duplicates.
=> Multiple model export issue is fixed

CDP4Orm/Dao/Revision/IRevisionDao.cs, CDP4Orm/Dao/Revision/RevisionDao.cs, CDP4Orm/Dao/Revision/RevisionRegistryInfo.cs, CDP4WebServices.API.Tests/Services/Revision/RevisionResolverTestFixture.cs, CDP4WebServices.API/Cdp4Bootstrapper.cs, CDP4WebServices.API/Modules/10-25/ApiBase.cs, CDP4WebServices.API/Modules/10-25/EngineeringModelApi.cs, CDP4WebServices.API/Modules/10-25/SiteDirectoryApi.cs, CDP4WebServices.API/Services/Protocol/IQueryParameters.cs, CDP4WebServices.API/Services/Protocol/QueryParameters.cs, CDP4WebServices.API/Services/Revision/IRevisionResolver.cs, CDP4WebServices.API/Services/Revision/RevisionResolver.cs
Added the possibility to get revisions by DateTime and or revision number.
=> Fixes GH98: timestamps in revision query parameters

CDP4Authentication/CDP4Authentication.csproj, CDP4DatabaseAuthentication/CDP4DatabaseAuthentication.csproj, CDP4Orm.Tests/CDP4Orm.Tests.csproj, CDP4Orm/AutoGenDao/IterationSetupDao.cs, CDP4Orm/CDP4Orm.csproj, CDP4Orm/Dao/Supplemental/IterationSetupDao.cs, CDP4WebServer/CDP4WebServer.csproj, CDP4WebService.Authentication/CDP4WebService.Authentication.csproj, CDP4WebServices.API.Tests/CDP4WebServices.API.Tests.csproj, CDP4WebServices.API.Tests/SideEffects/IterationSetupSideEffectTestFixture.cs, CDP4WebServices.API/CDP4WebServices.API.csproj, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/IterationSetupSideEffect.cs, CDP4WebServices.API/config_debug.json
=> [WIP] Bug/gh66 verify that iteration setup.is deleted behavior is as per 10 25; fixes #66

CDP4Authentication/CDP4Authentication.csproj, CDP4DatabaseAuthentication/CDP4DatabaseAuthentication.csproj, CDP4Orm.Tests/CDP4Orm.Tests.csproj, CDP4Orm/CDP4Orm.csproj, CDP4WebServer/CDP4WebServer.csproj, CDP4WebService.Authentication/CDP4WebService.Authentication.csproj, CDP4WebServices.API.Tests/CDP4WebServices.API.Tests.csproj, CDP4WebServices.API.Tests/SideEffects/EngineeringModelSetupSideEffectTestFixture.cs, CDP4WebServices.API/CDP4WebServices.API.csproj, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/EngineeringModelSetupSideEffect.cs
=> GH110-Verify behaviour of DomainFileStore creation or deletion when EngineeringModelSetup is updated; fixes #110

CDP4WebServices.API/Services/Operations/OperationProcessor.cs
When we would like to create SiteReferenceDataLibrary that contain two (or more) CompoundParamaterType, one of the loop responsible for the finding information about supplied thing type in the Create operation couldn't end the interval. It occurs because supplied thing was compare only with the container of the first CompoundParameterType and because of exception that this thing is not in the container, the loop was not able to jump into second CompoundParameterType in the List.
=> GH103-Internal-Server-Error-Invalid-Cast; fixes #103

CDP4WebServices.API/Modules/10-25/ApiBase.cs, compose.bat, docker-compose-nginx.yml, nginx/nginx.conf
Turns out this was a problem not just for nginx but for containers also! Async stream copying was not awaited and would cutoff for some reason on linux machines but not while debugging on windows.
Added simple nginx compose configuration to be able to spin up a local proxyserver to test against port 80.
NOTE: if nginx compose is used, webservices are no longer exposed on 5000.
=> Bad async multipart fix; fixes #112

CDP4Orm/AutoGenStructure/EngineeringModelDefinition.sql, CDP4Orm/CDP4Orm.csproj, CDP4Orm/MigrationScript/All_OnStartUpOnly_20200810_6_2_0_0_Autovacuum.sql
Fixes according to https://www.lob.com/blog/supercharge-your-postgresql-performance. Should eliminate need for manual and cron based autovacuum and improve long-term performance of the db.
=> Migration to set lower thresholds for table vacuum, and new EM generated SQL.; fixes #149

CDP4Orm/MigrationScript/All_OnStartUpOnly_20200810_6_2_0_0_Autovacuum.sql, CDP4WebServer/Program.cs
Autovacuum migration now inline with migration procedure and is doing and is doing way less useless stuff.
Server version in logs.
=> Autovacuum migration now inline with migration procedure

CDP4Orm/Dao/Supplemental/PersonDao.cs
Fixes a condition where upon updating a Person without providing a new password could erase the Salt property of that Person, effectively locking them out of the server.
=> Prevent override of Salt property on Person update

CDP4WebServices.API.Tests/SideEffects/DerivedQuantityKindSideEffectTestFixture.cs, CDP4WebServices.API.Tests/SideEffects/MeasurementScaleSideEffectTestFixture.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/CyclicRatioScaleSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/DerivedQuantityKindSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/IntervalScaleSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/LogarithmicScaleSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/MeasurementScaleSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/OrdinalScaleSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/RatioScaleSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/OperationSideEffectProcessor.cs
Other discovered issues which should be handled separately:
* There seems to be no (or at least some missing) server-side validation regarding property types; sending the wrong type for a property (e.g. a list of Guids instead of a list of OrderedItems) results in a generic server error instead of a proper server response.
* Acyclic validation errors are reported as generic 500s, leading to a poor way of handling them at the other end. Server errors should be properly split into categories with appropriate HTTP error codes and details/response bodies.
=> #165 New cyclic checks

CDP4WebServices.API/Cdp4Bootstrapper.cs, CDP4WebServices.API/Services/Authorization/ObfuscationService.cs
- [х] I have written a descriptive pull-request title
- [х] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/pulls) open
- [х] I have verified that I am following the CDP4-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-WebServices-Community-Edition/master/.github/CONTRIBUTING.md)
ModelLogEntries are now also obfuscated if `AffectedItemIid` contains any Iid of an obfuscated thing. Obfuscation service moved to request based service.
=> Enable obfuscation of ModelLogEntry

CDP4Authentication/AuthenticationPerson.cs, CDP4Orm/Dao/Authentication/AuthenticationDao.cs, CDP4WebServices.API/Modules/10-25/ApiBase.cs
When Person.IsActive is set to false and/or when Person.IsDeprecated is set to true, the WebService returns an "Unauthorized" (HTTP StatusCode 401) response.
=> [Fix] not IsActive or IsDeprecated returns unauthorized response

CDP4WebServices.API.Tests/Services/Authorization/PermissionServiceTestFixture.cs, CDP4WebServices.API/Services/Authorization/PermissionService.cs
Check SAME_AS_CONTAINER for container write access
=> Fixes #211 Check SAME_AS_CONTAINER for container write access

CDP4WebServices.API.Tests/Services/BusinessLogic/DefaultValueArrayFactoryTestFixture.cs, CDP4WebServices.API.Tests/SideEffects/ActualFiniteStateListSideEffectTestFixture.cs, CDP4WebServices.API.Tests/SideEffects/ParameterSideEffectTestFixture.cs, CDP4WebServices.API.Tests/SideEffects/ParameterTypeComponentSideEffectTestFixture.cs, CDP4WebServices.API.Tests/SideEffects/ParameterTypeSideEffectTestFixture.cs, CDP4WebServices.API.Tests/SideEffects/PossibleFiniteStateListSideEffectTestFixture.cs, CDP4WebServices.API.Tests/SideEffects/PossibleFiniteStateSideEffectTestFixture.cs, CDP4WebServices.API/Modules/10-25/EngineeringModelApi.cs, CDP4WebServices.API/Services/BusinessLogic/ICachedReferenceDataService.cs, CDP4WebServices.API/Services/BusinessLogic/IDefaultValueArrayFactory.cs, CDP4WebServices.API/Services/BusinessLogic/Implementation/CachedReferenceDataService.cs, CDP4WebServices.API/Services/BusinessLogic/Implementation/DefaultValueArrayFactory.cs, CDP4WebServices.API/Services/BusinessLogic/Implementation/StateDependentParameterUpdateService.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/DependentParameterTypeAssignmentSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/IndependentParameterTypeAssignmentSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/ParameterSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/ParameterTypeComponentSideEffect.cs
When a Parameter is created or updated reference data such as ParameterTypes and MeasurementScales are necessary to verify that the POST is correct and we do not end up with an incomplete dataset. Due to the fact that reference data and parameter data cannot be changed inside of one POST operation it is safe to query the reference data from the Cache tables of the database and store them in memory of the services to reuse for multiple operations. 
This is implemented in the `CachedReferenceDataService` and has led to a refactoring of the
- ParameterSideEffect
- DefaultValueArrayFactory
=> [Refactor] use of reference data and how it is queried from the database using a new CachedReferenceDataService; fixes #234

CDP4WebServices.API/Services/BusinessLogic/Implementation/DefaultValueArrayFactory.cs
Bug found by OHB. When copying EDs and there is a SFPT in the RDL chain, an exception would get thrown on the server stopping the copy due to cache dictionary not being cleaned up.
=> ParameterTypeAssignmentCache not being cleared would lead to duplicate keys exception

CDP4WebServices.API.Tests/Services/Supplemental/DomainFileStoreServiceTestFixture.cs, CDP4WebServices.API.Tests/Services/Supplemental/FolderServiceTestFixture.cs, CDP4WebServices.API.Tests/SideEffects/FileRevisionSideEffectTestFixture.cs, CDP4WebServices.API.Tests/SideEffects/FileSideEffectTestFixture.cs, CDP4WebServices.API.Tests/SideEffects/FolderSideEffectTestFixture.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/DomainFileStoreSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/FileRevisionSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/FileSideEffect.cs, CDP4WebServices.API/Services/Operations/SideEffects/Implementation/FolderSideEffect.cs, CDP4WebServices.API/Services/Supplemental/DomainFileStoreService.cs, CDP4WebServices.API/Services/Supplemental/FolderService.cs, CDP4WebServices.API/Services/Supplemental/IFileService.cs, CDP4WebServices.API/Services/Supplemental/IFolderService.cs, CDP4WebServices.API/Services/Supplemental/IterationService.cs, CDP4WebServices.API/config_test.json
[FIX] Model not loading when the participant is not allowed to see a DomainFileStore
=> [FIX] Model not loading when the participant is not allowed to see a DomainFileStore; fixes #280

CometServer.Tests/Authorization/PermissionServiceTestFixture.cs, CometServer/Authorization/PermissionService.cs
Implement create EngineeringModelSetup when PersonAccessRight is set to MODIFY_IF_PARTICIPANT on EngineeringModelSetup
=> Implement create engineering model setup on modify if participant; fixes #295

CometServer/Modules/10-25/ExchangeFileImportyApi.cs
[ADD] Extra logging to data seeds; fixes #302
=> [ADD] Extra logging to data seeds; fixes #302

CometServer/Startup.cs
CORS now exposes Http Header. Not exposing it provides exception on the DAL layer with Blazor WebAssembly because custom CDP Headers where hidden.
=> Allow CORS to expose custom Header (required for WASM)

CometServer/Helpers/Cdp4TransactionManager.cs, CometServer/Helpers/ICdp4TransactionManager.cs, CometServer/Services/Operations/SideEffects/Implementation/PublicationSideEffect.cs, CometServer/Services/Supplemental/IPermissionInstanceFilterService.cs, CometServer/Services/Supplemental/PermissionInstanceFilterService.cs
- [Refactor] Cdp4TransactionManager:add private rawSessionInstant field to limit the amount of times the dbase is hit
- Improve] documentation to make methods more explicit
=> [Improve] Cdp4TransactionManager -> add private rawSessionInstant field to limit the amount of times the dbase is hit

CometServer/Services/Resolve/ResolveService.cs
[FIX] No second partition lookup for SiteDirectory items in ResolvePartition; fixes #325
=> [FIX] No second partition lookup for SiteDirectory items in ResolvePartition; fixes #325

CometServer/Configuration/ServiceMessagingConfig.cs
update the `ServiceMessagingConfig` class to have a constructor used to set default values and update docs
=> [Update] ServiceMessagingConfig

CometServer/Services/Operations/SideEffects/Implementation/OptionSideEffect.cs
[FIX] Error creating new Option on model containing an Option Dependent Parameter; fixes #351
=> [FIX] Error creating new Option on model containing an Option Dependent Parameter; fixes #351

CometServer/Services/BusinessLogic/OldParameterContextProvider.cs
[FIX] Change Ownership on Parameter that is option dependent and overridden in EU overwrites existing values; fixes #353
=> [FIX] Change Ownership on Parameter that is option dependent and overridden in EU overwrites existing values; fixes #353

CDP4Orm/CDP4Orm.csproj, CometServer/CometServer.csproj, CometServer/Services/Operations/SideEffects/Implementation/ParameterSubscriptionValueSetSideEffect.cs
[FIX] Error saving value to ParameterSubscription on ParameterOverride; fixes #355
=> [FIX] Error saving value to ParameterSubscription on ParameterOverride; fixes #355

CDP4Orm/CDP4Orm.csproj, CometServer/CometServer.csproj, CometServer/Modules/10-25/ApiBase.cs, CometServer/Modules/10-25/EngineeringModelApi.cs, CometServer/Services/Headers/HttpConstants.cs
[ADD] CDPErrorTag in http response header; fixes #363
=> [ADD] CDP-Error-Tag in http response header; fixes #363

CometServer/CometServer.csproj, Dockerfile, VersionFileCreator/VersionFileCreator.csproj
[FIX] Version file update on runtime server instead of build server
=> [FIX] Version file update on runtime server instead of build server

.github/workflows/CodeQuality.yml, CometServer/Authentication/AuthenticationPluginInjector.cs
If a loaded plugin requires DLL that is not part of the referenced CDP4 COMET Server, those DLL are not loaded and the system is unable to resolve them, which leads to runtime exception and additional Authentication plugin may not work.
This code resolve this issue, tracks all DLL that has been discovered and loaded during the LoadPlugins process and help resolving missing DLL
=> Fix bug on DLL resolve for plugins
