CDP4Authentication/CDP4Authentication.csproj
CDP4DatabaseAuthentication/CDP4DatabaseAuthentication.csproj
CDP4Orm/AutoGenDao/ActualFiniteStateListDao.cs
CDP4Orm/AutoGenDao/ArrayParameterTypeDao.cs
CDP4Orm/AutoGenDao/DefinitionDao.cs
CDP4Orm/AutoGenDao/FileRevisionDao.cs
CDP4Orm/AutoGenDao/NestedElementDao.cs
CDP4Orm/AutoGenDao/ReferenceDataLibraryDao.cs
CDP4Orm/CDP4Orm.csproj
CDP4Orm/MigrationScript/SiteDirectory_20191121_4_0_0_2_Update_Revision_Management.sql
CDP4WebServer/CDP4WebServer.csproj

Added a check for existence of Container column on updated table in (SiteDirectory.revision_management) database trigger
- Bugfix extra semicolon in DAO files

Check for existence of Container column on updated table and bugfix extra semicolon in DAO

---

CDP4WebServices.API/Helpers/Cdp4TransactionManager.cs

remove () from single column update, removed sqlbuilder and make use of string interpolation

[Refactor] UPDATE command, remove mulit-column syntax (brackets) from the UPDATE statement; fixes #85

---

CDP4WebServices.API/MigrationEngine/MigrationEngine.cs
CDP4WebServices.API/Modules/10-25/EngineeringModelApi.cs
CDP4WebServices.API/Modules/10-25/ExchangeFileImportyApi.cs
CDP4WebServices.API/Modules/10-25/SiteDirectoryApi.cs
CDP4WebServices.API/Services/Authentication/UserValidator.cs
CDP4WebServices.API/Services/BusinessLogic/Implementation/EngineeringModelZipExportService.cs
CDP4WebServices.API/Services/BusinessLogic/Implementation/FileArchiveService.cs

- [s] I have written a descriptive pull-request title
- [s] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/pulls) open
- [s] I have verified that I am following the CDP4-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-WebServices-Community-Edition/master/.github/CONTRIBUTING.md)
- [s] I have provided test coverage for my change (where applicable)
Fixes rollback/commit errors on completed transactions.
Partly fixes IME [#184](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/184)

fixes #94: No more rollbacks or commits on completed transactions

---

CDP4WebServices.API.Tests/SideEffects/ActualFiniteStateListSideEffectTestFixture.cs
CDP4WebServices.API/Services/Operations/SideEffects/Implementation/ActualFiniteStateListSideEffect.cs

#32 save issue when changing state kind for an Actual Finite State

Editing StateKind of ActualFiniteState inside of ActualStateList update now possible.

---

CDP4WebServices.API/Configuration/DefaultsConfig.cs
CDP4WebServices.API/Modules/Authentication/AuthenticationModule.cs
CDP4WebServices.API/config_debug.json
CDP4WebServices.API/config_release.json
CDP4WebServices.API/config_test.json

[Update] geo location URL
[Disable] geo location service temporarily
The used geo service changed its URL and does not work properly. Because it is not an important functionality it is disabled. A separate issue is opened for this and will be investigated later.

Geo location disablement

---

CDP4WebServices.API.Tests/Services/Supplemental/DomainFileStoreServiceTestFixture.cs
CDP4WebServices.API.Tests/Services/Supplemental/FileServiceTestFixture.cs
CDP4WebServices.API.Tests/SideEffects/FileRevisionSideEffectTestFixture.cs
CDP4WebServices.API.Tests/SideEffects/FileSideEffectTestFixture.cs
CDP4WebServices.API.Tests/SideEffects/FolderSideEffectTestFixture.cs
CDP4WebServices.API/Modules/10-25/EngineeringModelApi.cs
CDP4WebServices.API/Services/Authorization/IPermissionService.cs
CDP4WebServices.API/Services/Authorization/PermissionService.cs
CDP4WebServices.API/Services/IRequestUtils.cs
CDP4WebServices.API/Services/Operations/SideEffects/Implementation/DomainFileStoreSideEffect.cs
CDP4WebServices.API/Services/Operations/SideEffects/Implementation/FileRevisionSideEffect.cs
CDP4WebServices.API/Services/Operations/SideEffects/Implementation/FileSideEffect.cs
CDP4WebServices.API/Services/Operations/SideEffects/Implementation/FolderSideEffect.cs
CDP4WebServices.API/Services/RequestUtils.cs
CDP4WebServices.API/Services/Supplemental/DomainFileStoreService.cs
CDP4WebServices.API/Services/Supplemental/FileService.cs
CDP4WebServices.API/Services/Supplemental/IDomainFileStoreService.cs
CDP4WebServices.API/Services/Supplemental/IFileService.cs
CDP4WebServices.API/Services/Supplemental/ServiceBase.cs
appveyor.yml

Added Permission checks for File.IsLocked, DomainFileStore.IsHidden and ownership of DomainFileStore, File and Folder.

Added Permission checks #111

---

CDP4Orm.Tests/CDP4Orm.Tests.csproj
CDP4Orm/AutoGenDao/ActualFiniteStateListDao.cs
CDP4Orm/AutoGenDao/ArrayParameterTypeDao.cs
CDP4Orm/AutoGenDao/BookDao.cs
CDP4Orm/AutoGenDao/CategoryDao.cs
CDP4Orm/AutoGenDao/DefinitionDao.cs
CDP4Orm/AutoGenDao/EnumerationValueDefinitionDao.cs
CDP4Orm/AutoGenDao/FileRevisionDao.cs
CDP4Orm/AutoGenDao/NestedElementDao.cs
CDP4Orm/AutoGenDao/NoteDao.cs
CDP4Orm/AutoGenDao/OptionDao.cs
CDP4Orm/AutoGenDao/PageDao.cs
CDP4Orm/AutoGenDao/ParameterTypeComponentDao.cs
CDP4Orm/AutoGenDao/ParametricConstraintDao.cs
CDP4Orm/AutoGenDao/PointDao.cs
CDP4Orm/AutoGenDao/PossibleFiniteStateDao.cs
CDP4Orm/AutoGenDao/QuantityKindFactorDao.cs
CDP4Orm/AutoGenDao/ReferenceDataLibraryDao.cs
CDP4Orm/AutoGenDao/RuleVerificationDao.cs
CDP4Orm/AutoGenDao/SectionDao.cs
CDP4Orm/AutoGenDao/TelephoneNumberDao.cs
CDP4Orm/AutoGenDao/UnitFactorDao.cs
CDP4Orm/CDP4Orm.csproj
CDP4Orm/Dao/Cache/CacheDao.cs
CDP4Orm/Dao/Revision/RevisionDao.cs
CDP4WebServices.API.Tests/CDP4WebServices.API.Tests.csproj
CDP4WebServices.API/CDP4WebServices.API.csproj
CDP4WebServices.API/config_debug.json
CDP4WebServices.API/config_test.json

Update to using Npgsql 4.1 and necessary changes/fixes.

Fixes #9 update to npgsql 4.1

---

CDP4Orm/CDP4Orm.csproj
CDP4Orm/MigrationScript/SiteDirectory_20200612_6_1_0_0_reset_statement_timeout.sql

Fixes #125 SET statement_timeout migration

---

CDP4WebServices.API/Services/Operations/OperationProcessor.cs

Delete File fix: Wrong data in BeforeDelete parameter.

Fixes #137 Delete File fix

---

.gitignore
README.md
appveyor.yml
cdp4ws-tests.nunit

add sonarcloud

---

CDP4WebServices.API.Tests/Services/Supplemental/ModelReferenceDataLibraryServiceTestFixture.cs
CDP4WebServices.API/Services/Supplemental/ModelReferenceDataLibraryService.cs

Looking up the Chain of RDL's did not search for nested SiteReferenceDatalibraries in the chain. Only the first level was found.
It does find it now.

Fixes #143 required rdl lookup

---

.gitignore
CDP4WebServices.API.Tests/Services/Supplemental/ModelReferenceDataLibraryServiceTestFixture.cs
CDP4WebServices.API/Services/Supplemental/ModelReferenceDataLibraryService.cs
README.md
appveyor.yml
cdp4ws-tests.nunit

Fixes #143 required rdl lookup (#144)

6.0.0-RC3 merge

---

CDP4WebServices.API.Tests/SideEffects/MeasurementScaleSideEffectTestFixture.cs
CDP4WebServices.API/Services/Operations/SideEffects/MeasurementScaleSideEffect.cs

Implement MeasurementScale cyclic check.

Implement MeasurementScale cyclic check

---

CDP4WebServices.API.Tests/SideEffects/DerivedQuantityKindSideEffectTestFixture.cs
CDP4WebServices.API.Tests/SideEffects/SpecializedQuantityKindSideEffectTestFixture.cs
CDP4WebServices.API/Services/Operations/SideEffects/Implementation/DerivedQuantityKindSideEffect.cs

Implement DerivedQuantityKind cyclic check.

Implement DerivedQuantityKind cyclic check

---

CDP4WebServices.API.Tests/SideEffects/IterationSetupSideEffectTestFixture.cs
CDP4WebServices.API.Tests/SideEffects/SiteReferenceDataLibrarySideEffectTestFixture.cs
CDP4WebServices.API/Services/Operations/SideEffects/Implementation/IterationSetupSideEffect.cs

Implement IterationSetup cyclic check.

Implement IterationSetup cyclic check

---

CDP4Orm/AutoGenStructure/EngineeringModelDefinition.sql
CDP4Orm/AutoGenStructure/SiteDirectoryDefinition.sql
CDP4Orm/CDP4Orm.csproj
CDP4Orm/MigrationScript/EngineeringModel_20210109_6_4_0_0_Model_Updates.sql
CDP4Orm/MigrationScript/Iteration_20210109_6_5_0_0_Model_Updates.sql
CDP4Orm/MigrationScript/SiteDirectory_20210108_6_3_0_0_Model_Updates.sql

WIP: SQL updates model 1.2.5

---

CDP4WebServices.API/CDP4WebServices.API.csproj
CDP4WebServices.API/Cdp4Bootstrapper.cs
CDP4WebServices.API/Configuration/AppConfig.cs
CDP4WebServices.API/Configuration/EmailConfig.cs
CDP4WebServices.API/Services/Email/EmailService.cs
CDP4WebServices.API/Services/Email/IEmailService.cs
CDP4WebServices.API/config_debug.json
CDP4WebServices.API/config_release.json

…nfig to config file
- Add email service ready for sending emails to the configured SMPT server
- Add config settings to the config file
- Add EmailService to bootstrapper so it is registered for the lifetime of the app

[Add] EmailService 

---

CDP4WebServices.API/Services/ChangeLog/ChangeLogService.cs

[Add] instrumentation NLog statements to ChangeLogService

[Add] instrumentation NLog statements to ChangeLogService

---

CDP4WebServices.API.Tests/ChangeLog/ChangeLogTestFixture.cs
CDP4WebServices.API/Services/ChangeLog/ChangeLogService.cs
CDP4WebServices.API/config_debug.json
CDP4WebServices.API/config_release.json
CDP4WebServices.API/config_test.json

Bugfix errors while changing a parameter's Scale or State when ChangeLog functionality is on.

Fixes #192 Change parameter's Scale or State

---

CDP4WebServices.API/Modules/10-25/ApiBase.cs
CDP4WebServices.API/Modules/10-25/EngineeringModelApi.cs
CDP4WebServices.API/Modules/10-25/ExchangeFileImportyApi.cs
CDP4WebServices.API/Modules/10-25/SiteDirectoryApi.cs
CDP4WebServices.API/Services/BusinessLogic/Implementation/EngineeringModelZipExportService.cs
CDP4WebServices.API/Services/Operations/OperationProcessor.cs

First part of implementation of #219

Default POST and GET implementation for Attachments

---

CDP4WebServices.API.Tests/OperationProcessorTestFixture.cs
CDP4WebServices.API.Tests/Services/Authorization/PermissionServiceTestFixture.cs
CDP4WebServices.API.Tests/Services/Supplemental/ModelReferenceDataLibraryServiceTestFixture.cs
CDP4WebServices.API.Tests/SideEffects/EngineeringModelSetupSideEffectTestFixture.cs
CDP4WebServices.API/Services/Authorization/PermissionService.cs
CDP4WebServices.API/Services/Operations/OperationProcessor.cs
CDP4WebServices.API/Services/Operations/SideEffects/Implementation/EngineeringModelSetupSideEffect.cs
CDP4WebServices.API/Services/Operations/SideEffects/Implementation/PersonPermissionSideEffect.cs
CDP4WebServices.API/Services/Supplemental/EngineeringModelSetupService.cs
CDP4WebServices.API/Services/Supplemental/IEngineeringModelSetupService.cs
CDP4WebServices.API/Services/Supplemental/ModelReferenceDataLibraryService.cs

A number of performance improvements refactoring the code to make use of the Cache tables in the database instead of the Views that incur heavy operations on the server due to the joins

[Improve] Query Performance to make first login faster; fixes #226

---

CDP4Orm.Tests/CDP4Orm.Tests.csproj
CDP4Orm/CDP4Orm.csproj
CDP4Orm/Dao/Utils.cs
CDP4WebServer/CDP4WebServer.csproj
CDP4WebServices.API.Tests/CDP4WebServices.API.Tests.csproj
CDP4WebServices.API/CDP4WebServices.API.csproj
CDP4WspDatabaseAuthentication.Tests/CDP4WspDatabaseAuthentication.Tests.csproj

Upgrade to COMET-SDK 8.0.0 and fix breaking changes

Upgrade to COMET-SDK 8.0.0 and fix breaking changes

---

CDP4WebServices.API/Services/Operations/SideEffects/Implementation/ModelCreator/ModelCreatorManager.cs

MRDL Name and ShortName changes on creating EngineeringModelSetup based on an existing EngineeringModelSetup

[FIX] MRDL Name and ShortName changes on creating EngineeringModelSetup; fixes #243

---

CDP4WebServer.IIS/packages.config
CDP4WebServices.API/Services/BusinessLogic/Implementation/CachedReferenceDataService.cs

SFTP creation was broken due to recent cache changes trying to gather information using the wrong services. fixes #254

SFTP cached ParameterType Assignments fixed; fixes #254

---

CDP4WebServices.API/Modules/10-25/EngineeringModelApi.cs
CDP4WebServices.API/Services/ChangeLog/ChangeLogService.cs
CDP4WebServices.API/Services/Operations/OperationProcessor.cs

Performance upgrade for ChangeLogService and OperationProcessor.

ChangeLogService and OperationProcessor performance upgrade; fixes #256

---

CDP4WebServices.API/Modules/10-25/SiteDirectoryApi.cs
CDP4WebServices.API/Services/Operations/OperationProcessor.cs

Bugfix OrderedItemList

---

CDP4Authentication/CDP4Authentication.csproj
CDP4Orm.Tests/CDP4Orm.Tests.csproj
CDP4Orm/CDP4Orm.csproj
CDP4WebServer.IIS/CDP4WebServer.IIS.csproj
CDP4WebServer.IIS/packages.config
CDP4WebServer/CDP4WebServer.csproj
CDP4WebService.Authentication/CDP4WebService.Authentication.csproj
CDP4WebServices.API.Tests/CDP4WebServices.API.Tests.csproj
CDP4WebServices.API/CDP4WebServices.API.csproj
CDP4WebServices.API/Cdp4Bootstrapper.cs
CDP4WebServices.API/MigrationEngine/MigrationEngine.cs
CDP4WebServices.API/Modules/10-25/ApiBase.cs
CDP4WebServices.API/Modules/10-25/CherryPickApi.cs
CDP4WebServices.API/Modules/10-25/EngineeringModelApi.cs
CDP4WebServices.API/Modules/10-25/ExchangeFileImportyApi.cs
CDP4WebServices.API/Modules/10-25/SiteDirectoryApi.cs
CDP4WebServices.API/Services/Headers/ContentTypeKind.cs
CDP4WebServices.API/Services/Headers/HeaderInfoProvider.cs
CDP4WebServices.API/Services/Headers/IHeaderInfoProvider.cs
CDP4WspDatabaseAuthentication.Tests/CDP4WspDatabaseAuthentication.Tests.csproj
Nuget.Config

- Add support for MessagePack respones (response only, no support for POST messages in MessagePack at this time)
- using Accept header to determine whether the server should respon with JSON or MessagePack

[Add] support for MessagePack; fixes #274

---

CDP4Authentication/EncryptionUtils.cs

remove use of obsolete classes/methods

Refactor encryption utils sha256 managed

---

CDP4Orm/Dao/Resolve/ContainerDao.cs
CDP4Orm/Dao/Resolve/ResolveDao.cs
CDP4Orm/Dao/Revision/RevisionDao.cs
CometServer/Authentication/AuthenticationPluginInjector.cs
CometServer/Services/ChangeLog/ChangeLogService.cs
CometServer/Services/JsonExchangeFile/JsonExchangeFileWriter.cs
CometServer/Services/Operations/SideEffects/Implementation/BooleanExpressionSideEffect.cs
CometServer/Services/Operations/SideEffects/Implementation/CategorySideEffect.cs
CometServer/Services/Operations/SideEffects/Implementation/ElementDefinitionSideEffect.cs
CometServer/Services/Operations/SideEffects/Implementation/RequirementsGroupSideEffect.cs
CometServer/Services/Resolve/ResolveService.cs

[SQ] CA1822 - Member does not access instance data and can be marked as static

[SQ] CA1822 - Member does not access instance data and can be marked as static

---

.github/workflows/CodeQuality.yml
.github/workflows/codeql-analysis.yml
CDP4Orm/CDP4Orm.csproj
CometServer/CometServer.csproj
CometServer/Modules/Root/RootModule.cs
CometServer/Resources/IResourceLoader.cs
CometServer/Resources/ResourceLoader.cs
CometServer/Resources/RootPage.html

[ADD] Show supported model versions on landing page; fixes #252

[ADD] Show supported model versions on landing page; fixes #252

---

CometServer/Services/Operations/OperationProcessor.cs

[FIX] Reordering Options throws an exception; fixes #127

[FIX] Reordering Options throws an exception; fixes #127

---

CometServer/Modules/10-25/EngineeringModelApi.cs
CometServer/Modules/10-25/SiteDirectoryApi.cs

[FIX] Error handling if a ResolvedException is thrown in Post request; fixes #145

[FIX] Error handling if a ResolvedException is thrown in Post request; fixes #145

---

CometServer.Tests/SideEffects/ParticipantSideEffectTestFixture.cs
CometServer/Services/Operations/SideEffects/Implementation/ParticipantSideEffect.cs

[FIX] Refuse the same Person to be added a s a Participant to an EngineeringModel; fixes #193

[FIX] Refuse the same Person to be added a s a Participant to an EngineeringModel; fixes #193

---

CometServer.Tests/SideEffects/ModelCreatorManagerTestFixture.cs
CometServer/Services/Operations/ModelCreatorManager.cs

[UPDATE] Only copy active IterationSetup on create EngineeringModelSetup from source model; fixes #59

 [UPDATE] Only copy active IterationSetup on create EngineeringModelSetup from source model; fixes #59

---

CometServer/CometServer.csproj
CometServer/Resources/ResourceLoader.cs
CometServer/VERSION
VersionFileCreator/Program.cs

Fix build problems due to VersionFileCreator issues

Fix build problems

---

CometServer/Extensions/StringExtensions.cs
CometServer/Modules/10-25/EngineeringModelApi.cs
CometServer/Modules/Constraints/EnumerableOfGuidRouteConstraint.cs
CometServer/Startup.cs

[Add]support for reading all EngineeringModel shallow ;Fixes #328

---

CometServer.Tests/SideEffects/ParameterSideEffectTestFixture.cs
CometServer/Services/Operations/SideEffects/Implementation/ParameterSideEffect.cs

[FIX] Duplicate ParameterTypes per ElementDefinition; fixes #269

[FIX] Duplicate ParameterTypes per ElementDefinition; fixes #269

---

CometServer.Tests/Configuration/AppConfigServiceTestFixture.cs
CometServer.Tests/Data/appsettings.json
CometServer.Tests/UtilsTestFixture.cs
CometServer/CometServer.csproj
CometServer/Configuration/AppConfig.cs
CometServer/Configuration/ServiceMessagingConfig.cs
CometServer/Modules/10-25/ApiBase.cs
CometServer/Modules/10-25/EngineeringModelApi.cs
CometServer/Modules/10-25/SiteDirectoryApi.cs
CometServer/Program.cs
CometServer/Startup.cs
CometServer/appsettings.Development.json
CometServer/appsettings.Production.json
docker-compose-dev.yml
docker-compose-nginx.yml
docker-compose.yml

closes #327 
Add RaabitMQ to notify a listener of changes to any data in the CDP4-COMET server
> NOTE: make sure that any calls to the queue are non-blocking and that the CDP4-COMET server is impacted as less as possible (we don't want this to slow us down)

[ADD] Added ThingsChangedMessage producing for post requests

---

.gitignore
CometServer/CometServer.csproj
CometServer/Modules/10-25/EngineeringModelApi.cs
CometServer/Modules/10-25/SiteDirectoryApi.cs
CometServer/Services/BusinessLogic/CachedReferenceDataService.cs
CometServer/Services/BusinessLogic/ICachedReferenceDataService.cs
CometServer/Services/Operations/SideEffects/Implementation/ParameterOverrideValueSetSideEffect.cs
CometServer/Services/Operations/SideEffects/Implementation/ParameterSubscriptionValueSetSideEffect.cs
CometServer/Services/Operations/SideEffects/Implementation/ParameterValueSetSideEffect.cs
CometServer/Services/Supplemental/IParameterService.cs
CometServer/Services/Supplemental/ParameterService.cs

Fix #335 
- Validation and cleanup done for ParameterValueSet, ParameterOverrideValueSet, ParameterSubscriptionValueSet using CDP4Common extensions for DTO Validation

Fix #335: Validation server-side implemented

---

CometServer/Authorization/PermissionService.cs

Fix #339 
- Only one call the the DB is done when checking Person permission. Here are new result (to be compare with previous result)
[new_after_caching_test_result.txt](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/files/14561346/new_after_caching_test_result.txt)
Remarks : I'm still concerned about the fact that we need to make a check for a read action based on the rule MODIFY_OWN_PERSON... TBD

Fix #339: Included cache routine for Person check

---

CDP4WebServices.API/Services/Authorization/PermissionService.cs

Fix #339: Included cache routine for Person check (#340)

---

CometServer/appsettings.Development.json
CometServer/appsettings.Production.json

…ion #341
[FIX] disable the message client, and therefor thing messages production #341

[FIX] disable the message client by default

---

CometServer/Helpers/Cdp4TransactionManager.cs
CometServer/Helpers/ICdp4TransactionManager.cs

[REVERT] Commit about adding rawSessionInstant in CDP4TransactionManager; fixes #358

[REVERT] Commit about adding rawSessionInstant in CDP4TransactionManager; fixes #358

---

CDP4Authentication.Tests/CDP4Authentication.Tests.csproj
CDP4Orm.Tests/CDP4Orm.Tests.csproj
CDP4Orm/CDP4Orm.csproj
CDP4WspDatabaseAuthentication.Tests/CDP4WspDatabaseAuthentication.Tests.csproj
CometServer.Tests/CometServer.Tests.csproj

- Update npgsql to version 8.0.4 (recently released)
- update test dependencies to (at this time) most recent version
integration test suite passed in the GH action

[Update] to npgsql version 8.0.4

---

CometServer/CometServer.csproj
CometServer/Services/Operations/ModelCreatorManager.cs
docker-compose.yml

[FIX] Missing ParameterTypeComponents in copy EngineeringModelSetup from Source

[FIX] Missing ParameterTypeComponents in copy EngineeringModelSetup from Source

---

CDP4Authentication.Tests/CDP4Authentication.Tests.csproj
CDP4Orm.Tests/CDP4Orm.Tests.csproj
CDP4Orm/CDP4Orm.csproj
CDP4WspDatabaseAuthentication.Tests/CDP4WspDatabaseAuthentication.Tests.csproj
CometServer/CometServer.csproj

- [Update] to CDP4-SDK version 27.3.4; 
- [Update] Mailkit 4.8.0
- [Update] test dependencies
unit tests and integration tests pass locally, running in GH action as well

[Update] CDP4-SDK, mailkit and test dependencies
